import ctypes
import multiprocessing
import os
import sys
import threading
from dataclasses import dataclass
from datetime import datetime
from multiprocessing.connection import Connection
from multiprocessing.sharedctypes import Synchronized
from multiprocessing.synchronize import Event
from time import perf_counter
from typing import Any

from mapchar.compression import CompressionFormat
from mapchar.console import get_progress
from mapchar.generator import FileNode, MapcharGenerator, Node
from mapchar.logger import log
from mapchar.utils.files import mapchar_open
from mapchar.utils.formatters import format_time


@dataclass
class GenerateOptions:
    """Options for the `generate` function"""

    filename: str | None
    buffering: int
    quiet_mode: bool
    delimiter: str
    wrange: tuple[str | None, str | None]
    threads: int
    flush_limit: int
    compresslevel: int | None
    compression: CompressionFormat | None = None


def generate(
    generator: MapcharGenerator,
    nodes: list[list[Node | FileNode]],
    stats: tuple[int, int],
    options: GenerateOptions,
) -> int:
    """Main function for generating wordlists

    Args:
        generator (MapcharGenerator): Generation class
        nodes (list[list[Node | FileNode]]): Nodes returned by `MapcharGenerator.parse`
        stats (tuple[int, int]): Statistics (number of generated bytes and word count)
        options (GenerateOptions): Generator options

    Returns:
        int: status code for CLI exit
    """
    start_time = None
    progress = multiprocessing.Value(ctypes.c_longlong, 0)
    total_bytes, total_words = stats

    if options.threads > 1:
        log.warning("Using multiple workers may result in interleaved output.")

    event = threading.Event()
    progress_thread = threading.Thread(
        target=get_progress,
        args=(event, progress),
        kwargs={"total": total_bytes},
        daemon=True,
    )

    show_progress_bar = (options.filename is not None) and (not options.quiet_mode)
    start_token, end_token = options.wrange
    stop_event = None

    def stop_progress() -> None:
        """Signal progress thread to stop and wait for it."""
        if progress_thread.is_alive() and not event.is_set():
            event.set()
            progress_thread.join()

    def start_progress_bar() -> None:
        """Start progress bar thread."""
        nonlocal start_time

        log.info(datetime.now().strftime("[bold]Started at %H:%M on %a, %b %d %Y.[/]"))

        if show_progress_bar and not progress_thread.is_alive():
            progress_thread.start()

        start_time = perf_counter()

    try:
        if options.threads > 1:
            # multi-process generation with writer process.
            writer_failed = multiprocessing.Event()
            writer_status_parent, writer_status_child = multiprocessing.Pipe()

            def writer_process(
                queue: multiprocessing.Queue,
                filename: str | None,
                buffering: int,
                compression: CompressionFormat | None,
                compresslevel: int | None,
                progress: Synchronized,
                stop_event: Event,
                writer_failed: Event,
                status_conn: Connection,
            ) -> None:
                """Write to output file when workers send data to the queue."""
                try:
                    with mapchar_open(
                        filename,
                        "a",
                        encoding="utf-8",
                        buffering=buffering,
                        compression=compression,
                        compresslevel=compresslevel,
                    ) as fp:
                        if not fp:
                            writer_failed.set()
                            stop_event.set()
                            try:
                                status_conn.send(False)
                            except Exception:
                                pass
                            return

                        try:
                            status_conn.send(True)
                        except Exception:
                            pass

                        try:
                            while True:
                                msg = queue.get()
                                if msg is None:
                                    break

                                data, processed = msg
                                if data:
                                    fp.write(data)
                                progress.value += processed
                        except BrokenPipeError:
                            stop_event.set()
                            devnull = os.open(os.devnull, os.O_WRONLY)
                            os.dup2(devnull, sys.stdout.fileno())

                except Exception as e:
                    stop_event.set()
                    writer_failed.set()
                    try:
                        status_conn.send(False)
                    except Exception:
                        pass
                    log.error(f"writer error: {e}")
                finally:
                    try:
                        status_conn.close()
                    except Exception:
                        pass

            def worker_process(
                generator: MapcharGenerator,
                nodes: list[list[Node | FileNode]],
                w_start_idx: int,
                t_count: int,
                queue: Any,
                delimiter: str,
                stop_event: Event,
                writer_failed: Event,
            ) -> None:
                """Worker process for word generation."""
                buf: list[str] = []
                buf_processed: int = 0
                flush_limit = options.flush_limit

                def safe_put(msg: tuple[str, int]) -> bool:
                    while not stop_event.is_set() and not writer_failed.is_set():
                        try:
                            queue.put(msg, timeout=0.5)
                            return True
                        except Exception:
                            continue
                    return False

                try:
                    w_start, expr_idx = generator.get_word_and_expr_at_index(
                        nodes, w_start_idx
                    )
                    worker_nodes = nodes[expr_idx:]

                    generated_count = 0
                    for token in generator.generate(
                        worker_nodes, start_token=w_start, end_token=None
                    ):
                        if generated_count >= t_count:
                            break
                        generated_count += 1
                        item = token + delimiter
                        buf.append(item)
                        buf_processed += len(item)

                        if buf_processed >= flush_limit:
                            data = "".join(buf)
                            processed_bytes = len(data.encode("utf-8"))
                            if not safe_put((data, processed_bytes)):
                                return
                            buf.clear()
                            buf_processed = 0

                    if buf:
                        data = "".join(buf)
                        processed_bytes = len(data.encode("utf-8"))
                        safe_put((data, processed_bytes))
                except Exception as e:
                    log.error(f"worker error: {e}")
                    stop_event.set()
                    writer_failed.set()

            queue: multiprocessing.Queue = multiprocessing.Queue(maxsize=128)
            stop_event = multiprocessing.Event()

            writer = multiprocessing.Process(
                target=writer_process,
                args=(
                    queue,
                    options.filename,
                    options.buffering,
                    options.compression,
                    options.compresslevel,
                    progress,
                    stop_event,
                    writer_failed,
                    writer_status_child,
                ),
            )
            writer.start()
            writer_status_child.close()

            try:
                writer_ok = writer_status_parent.recv()
            except EOFError:
                stop_event.set()
                writer.join()
                stop_progress()
                return 1
            finally:
                try:
                    writer_status_parent.close()
                except Exception:
                    pass

            if not writer_ok or writer_failed.is_set():
                stop_event.set()
                writer.join()
                stop_progress()
                return 1

            start_progress_bar()

            workers: list[multiprocessing.Process] = []

            start_idx = 0
            if start_token is not None:
                start_idx, _ = generator._calculate_skipped_stats_multi(
                    nodes, start_token
                )

            count = total_words
            step = count // options.threads
            remainder = count % options.threads
            current_idx = start_idx

            for i in range(options.threads):
                t_count = step + (1 if i < remainder else 0)
                if t_count == 0:
                    continue

                w_start_idx = current_idx
                current_idx += t_count

                p = multiprocessing.Process(
                    target=worker_process,
                    args=(
                        generator,
                        nodes,
                        w_start_idx,
                        t_count,
                        queue,
                        options.delimiter,
                        stop_event,
                        writer_failed,
                    ),
                )
                workers.append(p)
                p.start()

            for p in workers:
                p.join()

            stop_event.set()
            queue.put(None)
            writer.join()

            if writer_failed.is_set() or writer.exitcode not in (0, None):
                stop_progress()
                return 1

        else:
            buf = []
            buf_processed = 0
            flush_limit = options.flush_limit

            start_progress_bar()

            with mapchar_open(
                options.filename,
                "a",
                encoding="utf-8",
                buffering=options.buffering,
                compression=options.compression,
                compresslevel=options.compresslevel,
            ) as fp:
                if not fp:
                    stop_progress()
                    return 1

                for token in generator.generate(
                    nodes, start_token=start_token, end_token=end_token
                ):
                    item = token + options.delimiter
                    buf.append(item)
                    buf_processed += len(item)

                    if buf_processed >= flush_limit:
                        data = "".join(buf)
                        try:
                            fp.write(data)
                        except BrokenPipeError:
                            devnull = os.open(os.devnull, os.O_WRONLY)
                            os.dup2(devnull, sys.stdout.fileno())
                            return 0

                        progress.value += len(data.encode("utf-8"))
                        buf.clear()
                        buf_processed = 0

                if buf:
                    data = "".join(buf)
                    try:
                        fp.write(data)
                        fp.flush()
                    except BrokenPipeError:
                        devnull = os.open(os.devnull, os.O_WRONLY)
                        os.dup2(devnull, sys.stdout.fileno())
                        return 0
                    progress.value += len(data.encode("utf-8"))

    except KeyboardInterrupt:
        if stop_event is not None:
            stop_event.set()

        for child in multiprocessing.active_children():
            child.terminate()

        stop_progress()
        log.error("Generation stopped with keyboard interrupt!")
        return 1

    except Exception:
        stop_progress()
        raise

    stop_progress()

    if start_time is not None:
        elapsed = perf_counter() - start_time
        speed = int(total_words / elapsed) if elapsed > 0 else 0

        if (
            not (options.delimiter.endswith("\n") or options.quiet_mode)
            and options.filename is None
        ):
            sys.stdout.write("\n")
            sys.stdout.flush()

        log.info(
            f"[bold]Finished in [magenta]{format_time(elapsed)}[/magenta] ({speed} W/s).[/]"
        )
        return 0

    return 1
