import re
import sys
import tty
import ctypes
import termios
import threading
import multiprocessing

from dataclasses import dataclass
from datetime import datetime
from logging import ERROR
from typing import Any
from time import perf_counter
from fuse import BANNER

from fuse.logger import log
from fuse.args import create_parser
from fuse.console import get_progress
from fuse.utils.files import fuse_open
from fuse.utils.formatters import format_size, format_time, parse_size
from fuse.generator import ExprError, Node, FuseGenerator
from fuse.file_parser import InvalidSyntaxError, process_expr_file
from fuse.compression import (
    CompressionFormat,
    COMPRESSION_LEVEL_RANGES,
)
from multiprocessing.synchronize import Event
from multiprocessing.sharedctypes import Synchronized
from multiprocessing.queues import Queue
from multiprocessing.connection import Connection


@dataclass
class GenerateOptions:
    """Options for the `generate` function"""

    filename: str | None
    buffering: int
    quiet_mode: bool
    delimiter: str
    wrange: tuple[str | None, str | None]
    threads: int
    flush_limit: int
    compresslevel: int | None
    compression: CompressionFormat | None = None


def generate(
    generator: FuseGenerator,
    nodes: list[Node],
    stats: tuple[int, int],
    options: GenerateOptions,
) -> int:
    """Main function for generating wordlists

    Args:
        generator (FuseGenerator): Generation class
        nodes (list[Node]): Nodes returned by `FuseGenerator.parse`
        stats (tuple[int, int]): Statistics (number of generated bytes and word count)
        options (GenerateOptions): Generator options

    Returns:
        int: status code for CLI exit
    """
    start_time = None
    progress = multiprocessing.Value(ctypes.c_longlong, 0)
    total_bytes, total_words = stats

    if options.threads > 1:
        log.warning("Using multiple workers may result in interleaved output.")

    event = threading.Event()
    progress_thread = threading.Thread(
        target=get_progress,
        args=(event, progress),
        kwargs={"total": total_bytes},
        daemon=True,
    )

    show_progress_bar = (options.filename is not None) and (not options.quiet_mode)
    start_token, end_token = options.wrange
    stop_event = None

    def stop_progress() -> None:
        """Signal progress thread to stop and wait for it."""
        if progress_thread.is_alive() and not event.is_set():
            event.set()
            progress_thread.join()

    def start_progress_bar() -> None:
        """Start progress bar thread."""
        nonlocal start_time

        log.info(
            datetime.now().strftime("[bold]Started at %H:%M:%S on %a, %b %d %Y.[/]")
        )

        if show_progress_bar and not progress_thread.is_alive():
            progress_thread.start()

        start_time = perf_counter()

    try:
        if options.threads > 1:
            # multi-process generation with writer process.
            writer_failed = multiprocessing.Event()
            writer_status_parent, writer_status_child = multiprocessing.Pipe()

            def writer_process(
                queue: multiprocessing.Queue,
                filename: str | None,
                buffering: int,
                compression: CompressionFormat | None,
                compresslevel: int | None,
                progress: Synchronized,
                stop_event: Event,
                writer_failed: Event,
                status_conn: Connection,
            ) -> None:
                """Write to output file when workers send data to the queue."""
                try:
                    with fuse_open(
                        filename,
                        "a",
                        encoding="utf-8",
                        buffering=buffering,
                        compression=compression,
                        compresslevel=compresslevel,
                    ) as fp:
                        if not fp:
                            writer_failed.set()
                            stop_event.set()
                            try:
                                status_conn.send(False)
                            except Exception:
                                pass
                            return

                        try:
                            status_conn.send(True)
                        except Exception:
                            pass

                        while True:
                            msg = queue.get()
                            if msg is None:
                                break

                            data, processed = msg
                            if data:
                                fp.write(data)
                            progress.value += processed

                except Exception as e:
                    stop_event.set()
                    writer_failed.set()
                    try:
                        status_conn.send(False)
                    except Exception:
                        pass
                    log.error(f"writer error: {e}")
                finally:
                    try:
                        status_conn.close()
                    except Exception:
                        pass

            def worker_process(
                generator: FuseGenerator,
                nodes: list[Node],
                start_token: str | None,
                end_token: str | None,
                queue: Any,
                delimiter: str,
                stop_event: Event,
                writer_failed: Event,
            ) -> None:
                """Worker process for word generation."""
                buf: list[str] = []
                buf_processed: int = 0
                flush_limit = options.flush_limit

                def safe_put(msg: tuple[str, int]) -> bool:
                    while not stop_event.is_set() and not writer_failed.is_set():
                        try:
                            queue.put(msg, timeout=0.5)
                            return True
                        except Exception:
                            continue
                    return False

                try:
                    for token in generator.generate(
                        nodes, start_token=start_token, end_token=end_token
                    ):
                        item = token + delimiter
                        item_b = len(item.encode("utf-8"))

                        buf.append(item)
                        buf_processed += item_b

                        if buf_processed >= flush_limit:
                            if not safe_put(("".join(buf), buf_processed)):
                                return
                            buf.clear()
                            buf_processed = 0

                    if buf_processed > 0:
                        safe_put(("".join(buf), buf_processed))

                except Exception as e:
                    log.error(f"worker error: {e}")
                    stop_event.set()
                    writer_failed.set()

            queue: Queue = multiprocessing.Queue(maxsize=128)
            stop_event = multiprocessing.Event()

            writer = multiprocessing.Process(
                target=writer_process,
                args=(
                    queue,
                    options.filename,
                    options.buffering,
                    options.compression,
                    options.compresslevel,
                    progress,
                    stop_event,
                    writer_failed,
                    writer_status_child,
                ),
            )
            writer.start()
            writer_status_child.close()

            try:
                writer_ok = writer_status_parent.recv()
            except EOFError:
                stop_event.set()
                writer.join()
                stop_progress()
                return 1
            finally:
                try:
                    writer_status_parent.close()
                except Exception:
                    pass

            if not writer_ok or writer_failed.is_set():
                stop_event.set()
                writer.join()
                stop_progress()
                return 1

            start_progress_bar()

            workers: list[multiprocessing.Process] = []

            start_idx = 0
            if start_token is not None:
                start_idx, _ = generator._calculate_skipped_stats(nodes, start_token)

            count = total_words
            step = count // options.threads
            remainder = count % options.threads
            current_idx = start_idx

            for i in range(options.threads):
                t_count = step + (1 if i < remainder else 0)
                if t_count == 0:
                    continue

                if i == 0:
                    w_start = start_token
                else:
                    w_start = generator.get_word_at_index(nodes, current_idx - 1)

                current_idx += t_count
                w_end = generator.get_word_at_index(nodes, current_idx - 1)

                p = multiprocessing.Process(
                    target=worker_process,
                    args=(
                        generator,
                        nodes,
                        w_start,
                        w_end,
                        queue,
                        options.delimiter,
                        stop_event,
                        writer_failed,
                    ),
                )
                workers.append(p)
                p.start()

            for p in workers:
                p.join()

            stop_event.set()
            queue.put(None)
            writer.join()

            if writer_failed.is_set() or writer.exitcode not in (0, None):
                stop_progress()
                return 1

        else:
            buf = []
            buf_processed = 0
            flush_limit = options.flush_limit

            start_progress_bar()

            with fuse_open(
                options.filename,
                "a",
                encoding="utf-8",
                buffering=options.buffering,
                compression=options.compression,
                compresslevel=options.compresslevel,
            ) as fp:
                if not fp:
                    stop_progress()
                    return 1

                for token in generator.generate(
                    nodes, start_token=start_token, end_token=end_token
                ):
                    item = token + options.delimiter
                    item_b = len(item.encode("utf-8"))

                    buf.append(item)
                    buf_processed += item_b

                    if buf_processed >= flush_limit:
                        fp.write("".join(buf))
                        progress.value += buf_processed
                        buf.clear()
                        buf_processed = 0

                if buf_processed > 0:
                    if buf:
                        fp.write("".join(buf))
                    progress.value += buf_processed

    except KeyboardInterrupt:
        if stop_event is not None:
            stop_event.set()

        for child in multiprocessing.active_children():
            child.terminate()

        stop_progress()
        log.error("Generation stopped with keyboard interrupt!")
        return 1

    except Exception:
        stop_progress()
        raise

    stop_progress()

    if start_time is not None:
        elapsed = perf_counter() - start_time
        speed = int(total_words / elapsed) if elapsed > 0 else 0

        if not options.delimiter.endswith("\n") and options.filename is None:
            sys.stdout.write("\n")
            sys.stdout.flush()

        log.info(
            f"[bold]Finished in [magenta]{format_time(elapsed)}[/magenta] ({speed} W/s).[/]"
        )
        return 0

    return 1


def pause(prompt: str = "\u203a Press the Enter key to continue") -> bool:
    """Pause execution and wait for user input in terminal."""

    # ignores if interactive prompt is not supported
    if not sys.stdin.isatty():
        return True

    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)

    try:
        sys.stderr.write(prompt)
        sys.stderr.flush()

        tty.setraw(fd)

        while True:
            ch = sys.stdin.read(1)
            if ch in ("\r", "\n"):
                break
            elif ch == "\x03":
                raise KeyboardInterrupt

        sys.stderr.write("\r\033[K")
        sys.stderr.flush()

        return True

    except KeyboardInterrupt:
        sys.stderr.write("\r\n")
        sys.stderr.flush()
        return False

    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)


def format_expression(expression: str, files: list[str]) -> tuple[str, list[str]]:
    """Returns the expression with the list of files for word generation."""
    files_out: list[str] = []

    for file_path in files:
        # replaces inline inclusions (starting with "//")
        # example: fuse '/d^' '//[2-5]/d' -> '/d[2-5]/d'
        if file_path.startswith("//"):
            inline = file_path.replace("//", "", 1)
            expression = re.sub(r"(?<!\\)\^", lambda m: inline, expression, count=1)
        else:
            files_out.append(file_path)

    return expression, files_out


def print_info(
    s_words: int, estimated_size: str, compressor: None | str = None
) -> None:
    """Displays generation statistics and information before execution."""
    if compressor is None:
        log.info(
            BANNER
            + f"\nFuse will generate [bold rgb(255,120,0)]{s_words:,} entries[/] "
            f"({estimated_size})."
        )
    else:
        log.info(
            BANNER
            + f"\nFuse will generate [bold rgb(255,120,0)]{s_words:,} entries[/] "
            f"({estimated_size} [underline]uncompressed[/], {compressor})."
        )


def main() -> int:
    """Main entry point for the Fuse CLI. Returns the exit status code."""
    parser = create_parser()
    args = parser.parse_args()

    sys.setrecursionlimit(4000)

    if args.pattern is None and args.expr_file is None:
        parser.print_help(sys.stderr)
        return 1

    if not (1 <= args.workers <= 64):
        log.error(
            f"invalid number of workers ({args.workers}). choose a value between 1 and 64."
        )
        return 1

    # -----------------------------------------------
    # checks if the specified compression level (-l)
    # is supported by the selected format (-z)
    # -----------------------------------------------
    compresslevel = args.compresslevel
    if args.compress is not None:
        if compresslevel is not None:
            min_level, max_level = COMPRESSION_LEVEL_RANGES[args.compress]

            if not (min_level <= compresslevel <= max_level):
                log.error(f"{args.compress}: level must be {min_level}-{max_level}.")
                return 1

    elif compresslevel is not None:
        log.error("compression level (-l/--compresslevel) requires -z/--compress.")
        return 1

    if args.quiet:
        log.setLevel(ERROR)

    buffer_size = args.buffer

    if isinstance(buffer_size, str):
        try:
            buffer_size = parse_size(buffer_size)
            if buffer_size < 1:
                raise ValueError("unbuffered mode is not supported.")
        except ValueError as e:
            log.error(f"invalid buffer size: {e}")
            return 1

    if args.compress and args.output is None:
        log.error("compression requires -o/--output to specify an output file.")
        return 1

    try:
        flush_limit = parse_size(args.flush)
    except ValueError as e:
        log.error(f"invalid flush size: {e}")
        return 1

    gen_options = GenerateOptions(
        filename=args.output,
        buffering=buffer_size,
        quiet_mode=args.quiet,
        delimiter=args.delimiter,
        wrange=(args.start, args.end),
        threads=args.workers,
        compression=args.compress,
        flush_limit=flush_limit,
        compresslevel=compresslevel,
    )

    generator = FuseGenerator()

    # file mode (-f/--file)
    if args.expr_file is not None:
        if args.start or args.end:
            log.error("--start/--end are not supported with expression files.")
            return 1
        if args.workers > 1:
            log.error("multiple workers are not supported with expression files.")
            return 1

        # only errors
        log.setLevel(ERROR)

        try:
            for d in process_expr_file(args.expr_file):
                if d is None:
                    return 1

                expression, expr_files = d

                try:
                    tokens = generator.tokenize(expression)
                    nodes = generator.parse(tokens, files=(expr_files or None))
                    # calculates statistics for the `generate` call
                    s_bytes, s_words = generator.stats(
                        nodes, delimiter_len=len(args.delimiter)
                    )
                except ExprError as e:
                    log.error(e)
                    return 1

                stats = (s_bytes, s_words)

                ret_code = generate(generator, nodes, stats, gen_options)
                if ret_code != 0:
                    return ret_code

        except InvalidSyntaxError as e:
            log.error(e)

            return 1

        return 0

    expression, proc_files = format_expression(args.pattern, args.files)

    try:
        try:
            tokens = generator.tokenize(expression)
            nodes = generator.parse(tokens, files=(proc_files or None))
            # number of bytes (`s_bytes`) and the number of words (`s_words`)
            # to be generated
            s_bytes, s_words = generator.stats(
                nodes,
                delimiter_len=len(args.delimiter),
                start_token=args.start,
                end_token=args.end,
            )
        except ExprError as e:
            log.error(e)

            return 1

        estimated_size = format_size(s_bytes, d=2)

        print_info(s_words, estimated_size, compressor=args.compress)
    except (OverflowError, ValueError):
        log.error("Overflow Error! Is the expression correct?")

        return 1

    if not (args.quiet or args.non_interactive) and not pause():
        return 0

    stats = (s_bytes, s_words)

    try:
        return generate(generator, nodes, stats, gen_options)
    except KeyboardInterrupt:
        log.error("Unexpected keyboard interruption!")
    finally:
        sys.stdout.write("\033[?25h")  # fix cursor bug

    return 1
